C        Generated by TAPENADE     (INRIA, Tropics team)
C  Tapenade 3.9 (r5096) - 24 Feb 2014 16:53
C
C  Differentiation of func in forward (tangent) mode:
C   variations   of useful results: y
C   with respect to varying inputs: b
C   RW status of diff variables: y:out b:in
C
      SUBROUTINE FUNC_D(a, b, bd, xold, y, yd)
      IMPLICIT NONE
      DOUBLE PRECISION a(4, 4), b(4), xold(4), y, xnew(4), temp, ep
      DOUBLE PRECISION bd(4), xoldd(4), yd, xnewd(4), tempd
      INTEGER it, i, j, n, flag, z
      INTRINSIC ABS
      DOUBLE PRECISION abs0
      INTEGER ii1
      ep = 1e-15
      z = 1
C	  A = transpose(reshape((A),shape(A)))
      temp = 0
      flag = 1
      DO ii1=1,4
        xoldd(ii1) = 0.D0
      ENDDO
      DO ii1=1,4
        xnewd(ii1) = 0.D0
      ENDDO
      DO WHILE (flag .EQ. 1)
C	    print *,z
C            z=z+1
        DO i=1,4
          tempd = 0.D0
          DO j=1,4
            IF (i .NE. j) THEN
              tempd = tempd + a(i, j)*xoldd(j)
              temp = temp + a(i, j)*xold(j)
            END IF
          ENDDO
          xnewd(i) = (bd(i)-tempd)/a(i, i)
          xnew(i) = 1.0/a(i, i)*(b(i)-temp)
          temp = 0
        ENDDO
C            print *,xNew(i)
C		If the difference between the all values of xNew(i) and xOld(i) is less than or equal to ep then flag is set to 0.		
        DO j=1,4
          IF (xnew(j) - xold(j) .GE. 0.) THEN
            abs0 = xnew(j) - xold(j)
          ELSE
            abs0 = -(xnew(j)-xold(j))
          END IF
          IF (abs0 .LE. ep) THEN
            flag = 0
          ELSE
            GOTO 100
          END IF
        ENDDO
        GOTO 110
 100    flag = 1
 110    DO j=1,4
          xoldd(j) = xnewd(j)
          xold(j) = xnew(j)
        ENDDO
      ENDDO
      CALL OBJ_D(xold, xoldd, y, yd)
      END
