1 iterativesolver: (TC33) External procedure shape is not declared
2 iterativesolver: (TC37) Return type of function shape set by implicit rule to REAL
3 iterativesolver: (TC33) External procedure reshape is not declared
4 iterativesolver: (TC37) Return type of function reshape set by implicit rule to REAL
5 iterativesolver: (TC33) External procedure transpose is not declared
6 iterativesolver: (TC37) Return type of function transpose set by implicit rule to REAL
7 iterativesolver: (TC16) Type mismatch in assignment: DOUBLE PRECISION[4,4] receives REAL
8 iterativesolver: (TC16) Type mismatch in assignment: DOUBLE PRECISION[4] receives INTEGER[4]
9 iterativesolver: (TC16) Type mismatch in assignment: DOUBLE PRECISION[4] receives INTEGER[4]
