C        Generated by TAPENADE     (INRIA, Tropics team)
C  Tapenade 3.9 (r5096) - 24 Feb 2014 16:53
C
C  Differentiation of obj in forward (tangent) mode:
C   variations   of useful results: y
C   with respect to varying inputs: xold
C
      SUBROUTINE OBJ_D(xold, xoldd, y, yd)
      IMPLICIT NONE
      DOUBLE PRECISION xold(4), y
      DOUBLE PRECISION xoldd(4), yd
      INTRINSIC DLOG
      INTRINSIC EXP
      DOUBLE PRECISION arg1
      DOUBLE PRECISION arg1d
      arg1d = 2*xold(2)*xoldd(2)
      arg1 = xold(2)**2
      yd = 3*xold(1)**2*xoldd(1) + arg1d/arg1 + xoldd(3)*EXP(xold(3)) + 
     +  4*xoldd(4)
      y = xold(1)**3 + DLOG(arg1) + EXP(xold(3)) + 4*xold(4)
      END
